scene.onOverlapTile(SpriteKind.Player, sprites.castle.tileDarkGrass1, function (sprite, location) {
    info.startCountdown(10)
    music.play(music.melodyPlayable(music.beamUp), music.PlaybackMode.InBackground)
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    Shark.setImage(img`
        .................ccfff..............
        ................cddbbf..............
        ...............cddbbf...............
        .........ffffffccbbcf...............
        ......fffbbbbbbbbcccff..............
        .....fbbbbbbbbbbbbbbbcfff......ccccc
        .....bcbbbbbffbcbcbbbbcccff...cdbbbc
        .....bbb1111ffbbcbcbbbcccccffcddbbc.
        .....fb11111111bcbcbbbcccccccbdbbf..
        ......fccc33c11bbbbbbcccccccccbbcf..
        .......fc131cc11bbbbccccccccffbccf..
        ........f33c1111bbbcccccbdbc..fbbcf.
        .........ff1111cbbbfdddddcc....fbbf.
        ...........ccc1fbdbbfddcc.......fbbf
        ..............ccfbdbbfc..........fff
        .................fffff..............
        `)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.doorLockedSouth, function (sprite, location) {
    game.gameOver(true)
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    Shark.setImage(img`
        ..............fffcc.................
        ..............fbbddc................
        ...............fbbddc...............
        ...............fcbbccffffff.........
        ..............ffcccbbbbbbbbfff......
        ccccc......fffcbbbbbbbbbbbbbbbf.....
        cbbbdc...ffcccbbbbcbcbffbbbbbcb.....
        .cbbddcffcccccbbbcbcbbff1111bbb.....
        ..fbbdbcccccccbbbcbcb11111111bf.....
        ..fcbbcccccccccbbbbbb11c33cccf......
        ..fccbffccccccccbbbb11cc131cf.......
        .fcbbf..cbdbcccccbbb1111c33f........
        .fbbf....ccdddddfbbbc1111ff.........
        fbbf.......ccddfbbdbf1ccc...........
        fff..........cfbbdbfcc..............
        ..............fffff.................
        `)
})
let Shark: Sprite = null
game.splash("Shark Story")
game.showLongText("Oyunun Amacı: Labirent içerisindeki balıkları 10 saniye içerisinde bulup, avlamaktır.", DialogLayout.Bottom)
game.showLongText("Yosunlar üzerine gelerek süreni tekrar başa alabilirsin", DialogLayout.Bottom)
game.showLongText("Oyuna Başla", DialogLayout.Bottom)
Shark = sprites.create(img`
    ..............fffcc.................
    ..............fbbddc................
    ...............fbbddc...............
    ...............fcbbccffffff.........
    ..............ffcccbbbbbbbbfff......
    ccccc......fffcbbbbbbbbbbbbbbbf.....
    cbbbdc...ffcccbbbbcbcbffbbbbbcb.....
    .cbbddcffcccccbbbcbcbbff1111bbb.....
    ..fbbdbcccccccbbbcbcb11111111bf.....
    ..fcbbcccccccccbbbbbb11c33cccf......
    ..fccbffccccccccbbbb11cc131cf.......
    .fcbbf..cbdbcccccbbb1111c33f........
    .fbbf....ccdddddfbbbc1111ff.........
    fbbf.......ccddfbbdbf1ccc...........
    fff..........cfbbdbfcc..............
    ..............fffff.................
    `, SpriteKind.Player)
controller.moveSprite(Shark, 150, 150)
tiles.setCurrentTilemap(tilemap`level1`)
tiles.placeOnRandomTile(Shark, sprites.dungeon.doorOpenEast)
scene.cameraFollowSprite(Shark)
info.startCountdown(10)
music.play(music.stringPlayable("G B A G C5 B A B ", 120), music.PlaybackMode.LoopingInBackground)
